function buttons() {
  x = 40;
  y = 30;
  this.add_f = createButton('Задать функцию');
  this.add_f.position(x + 5, y + 190);
  this.add_f.style('font-size', '18px');
  this.add_f.size(190);
  this.add_r = createButton('Задать промежуток');
  this.add_r.position(x + 405, y + 190 + 40);
  this.add_r.style('font-size', '18px');
  this.add_r.size(190);
  this.norm_f = createButton('Задать един. ф-цию');
  this.norm_f.position(x + 5, y + 190 + 40);
  this.norm_f.style('font-size', '18px');
  this.norm_f.size(190);
  this.draw_f = createButton('Печать ф-цию');
  this.draw_f.position(x + 205, y + 190);
  this.draw_f.style('font-size', '18px');
  this.draw_f.size(190);
  this.drawn_f = createButton('Печать един. ф-цию');
  this.drawn_f.position(x + 205, y + 190 + 40);
  this.drawn_f.style('font-size', '18px');
  this.drawn_f.size(190);
  this.rand_f = createButton('Monte-Carlo V1');
  this.rand_f.position(x + 405, y + 190);
  this.rand_f.style('font-size', '18px');
  this.rand_f.size(190);
  this.rand_f2 = createButton('Monte-Carlo V3');
  this.rand_f2.position(x + 805, y + 190);
  this.rand_f2.style('font-size', '18px');
  this.rand_f2.size(190);
  this.rans = createButton('Задать повторы');
  this.rans.position(x + 605, y + 190 + 40);
  this.rans.style('font-size', '18px');
  this.rans.size(190);
  this.rep = createButton('Задать кол-во точек');
  this.rep.position(x + 605, y + 190);
  this.rep.style('font-size', '18px');
  this.rep.size(190);
  this.help = createButton('Помощь');
  this.help.position(x + 805, y + 190 + 40);
  this.help.style('font-size', '18px');
  this.help.size(190);
  this.add_f.mousePressed(AddFucntion);
  this.add_r.mousePressed(AddRange);
  this.norm_f.mousePressed(SetNFucntion);
  this.draw_f.mousePressed(DrawFunction);
  this.drawn_f.mousePressed(DrawNFunction);
  this.rand_f.mousePressed(monte1);
  this.rand_f2.mousePressed(monte2);
  this.rans.mousePressed(SetRans);
  this.rep.mousePressed(SetRep);
  this.help.mousePressed(Help);
}